### PR TITLE
stackoverflow_analysis_2021

### PR DESCRIPTION
**Pull request by bhartijoshi04**

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
Could you let me know the issue assigned. 
+ the thing is we don't need different ipynb file. look at the backlog folder. many people has created different ipynb file. The main idea is add on to the existing ipynb file.

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
Kindly move to backlog folder

**Comment by bhartijoshi04** [comment]
I am unable to do so, my forked repository isn't up to date. I did try to fork again but I am unable to see the backlog folder in forked repository
However, I did commit changes in the main file.
You can go through that @sanjay-kv .

**Comment by sanjay-kv** [comment]
you gotta do git pull in commant promt.

**Comment by bhartijoshi04** [comment]
@sanjay-kv Now you can check, I've added the 2021.CSV file to the data folder and updated the analysis notebook

**Comment by sanjay-kv** [comment]
Data folder is for only CSV files. 
Push the main files to backlog, I will review it and merge with main file later

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
sorry, there are changes required. i commented the same.

**Comment by bhartijoshi04** [comment]
I've updated the analysis file as per your previous analysis with the markdown included,

**Comment by bhartijoshi04** [comment]
> Data folder is for only CSV files. Push the main files to backlog, I will review it and merge with main file later

Yeah, I've added the csv file only in the data folder and the ipynb file of stackoverflow_analysis, I've updated the 2021_stack's EDA into it.

**Comment by sanjay-kv** [comment]
can you fix the confliclts files, then I will merge it

**Comment by sanjay-kv** [comment]
As you spent more time on this I upgraded the labels to level 2

**Comment by bhartijoshi04** [comment]
I'll add it separately in the backlog folder, you can review it from there after then.

**Pull request closed without merging**
