### PR TITLE
Code Added

### PR DESCRIPTION
**Pull request by merciajeno**
Aim:To find the best programming language among beginners and experts( in the year 2023)
Procedure:
1. Clean the dataset(eg: convert 'less than 1 year' to 1 , remove Nan etc.)
2. created datasets for beginner and expert
3. Analysed the languages used and found the frequency
4. Plotted the observation in bar plots and pie charts

Issue:https://github.com/Recode-Hive/Stackoverflow-Analysis/issues/90

### CODE REVIEW

**Comment by sanjay-kv** [comment]
Can u tag the issue created for this .

**Comment by merciajeno** [comment]
Tagged the issue in the above comment

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
We dont need different ipynb for different commits, you can check in the backlog folder how many of them I moved to there. so maybe you can add to our main code file.

**Comment by merciajeno** [comment]
I don't know why but I am unable to add my code to the main code. So I have added it to the backlog section

**Comment by merciajeno** [comment]
@sanjay-kv , can you review the code and check if I have to make any more changes?

**Pull request merged**
