### PR TITLE
Added 2021 and 2022 data with aanalysis and updated streamlit app

### PR DESCRIPTION
**Pull request by NIKITA320495**

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
Awesome @NIKITA320495 

some suggestions for you would be : adding description on the changes made in the PR. 
incoperating bit more coding comments. so it will improve readbility and understanding for future developments.

**Comment by sanjay-kv** [comment]
Could you check and reply here regarding the Streamlit app and Streamlit on Snowflakes are same thing? @NIKITA320495

**Comment by Leena2403** [comment]
hello @sanjay-kv sir, please assign me the PR as well. As Nikita and I collaborated on this one as well. And yes, we'll make sure to add proper comments for readability from now on. As for Snowflakes, we never worked on it, so not sure.

**Comment by sanjay-kv** [comment]
leena just raise one more PR and link the PR to there. and I will assign same level. it has been noted leaderboard is not fetching two people on co-authored commits. 

1. Raise an new PR by changing readme file 
2. Explain in the description you worked on this PR with links
3. I will merge and give the same level @NIKITA320495 has got.

**Comment by Leena2403** [comment]
Ok @sanjay-kv  sir !

**Pull request merged**
