### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Sibam-Paul**
Made the link functioning issue #30 
image

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
Good to go

**Comment by Sibam-Paul** [comment]
@sanjay-kv Can u please give level1 tag as i think it should be . Please confirm

**Comment by Sibam-Paul** [comment]
@sanjay-kv please give level1 to it

**Comment by sanjay-kv** [comment]
sorry it a link, cant give level 1. documentation we hardly give any levels.

**Comment by Sibam-Paul** [comment]
ok

**Pull request merged**
