### PR TITLE
Heat Map Added for 2018,2019,2020 survey Data

### PR DESCRIPTION
**Pull request by Saksh8**
I have added the Python code to add a heat map for all the features present in the survey table of the 2018,2019 and 2020 dataset.I have used matplotlib for doing the same.

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
Good to go

**Comment by sanjay-kv** [comment]
There is a conflict on the above file, make sure to do pull changes before you push .

Could you try from your end again, cant change in the web editor from my side @Saksh8

**Comment by Saksh8** [comment]
Conflict Resolved

**Comment by sanjay-kv** [comment]
@Saksh8 Assigned it has level3 for your good work. Thanks

**Comment by sanjay-kv** [comment]
/@Saksh8 are you good at sql and R

**Comment by Saksh8** [comment]
I'm good at SQL

**Comment by Saksh8** [comment]
Not well versed with R but I can try if needed

**Comment by sanjay-kv** [comment]
I might need your help: can i get your LinkedIn?

**Comment by Saksh8** [comment]
[https://www.linkedin.com/in/aastha-ojha-210734227/]

**Pull request merged**
