### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Navyazitya**
Data visualizations of 2018 stackoverflow survey:
I removed the outliers detected and then created univariate and bivariate analysis which shows the relationship established between each column of the stackoverflow data.

### CODE REVIEW

**Comment by sanjay-kv** [comment]
@Navyazitya This is related to which issue?

**Comment by Navyazitya** [comment]
> @Navyazitya This is related to which issue?

EDA for the data analysis sir. 
Previously I did outlier detection and now I added different visualizations to it.

**Comment by sanjay-kv** [comment]
Next Time when you commit type # and refer the issue created else its creating confusion. and may be attach screenshot for reference. so I can quickly merge

**Review by sanjay-kv — APPROVED** [review]

**Comment by Navyazitya** [comment]
> Next Time when you commit type # and refer the issue created else its creating confusion. and may be attach screenshot for reference. so I can quickly merge

Done sir. I will do that.

**Pull request merged**
