### PR TITLE
Added Catboost Regressor

### PR DESCRIPTION
**Pull request by Maryam-Sikander**
Hello PA,
I have used CatBoost Regressor for model training, and it showed a slight improvement compared to other models
Screenshot 2024-05-12 223435

During code execution, I encountered these issues and fixed them:
1. Renamed the Seaborn background theme to resolve an OSError issue during code execution. The updated theme aligns with the existing style.
Screenshot 2024-05-12 223850

2. Fixed the syntax for using `get_function`, which was previously causing the mean of a categorical column to be calculated:
Screenshot 2024-05-12 223955

### CODE REVIEW

**Comment by sanjay-kv** [comment]
can you refer to the issue you raised.
you can do that by typing # and find relevant issue .
sample https://github.com/Recode-Hive/Stackoverflow-Analysis/issues/74

**Comment by Maryam-Sikander** [comment]
@sanjay-kv, this is the issue I raised #68
Kindly check it!

**Comment by sanjay-kv** [comment]
There is conflicts in the above files, try always pull changes before you push

**Comment by Maryam-Sikander** [comment]
@sanjay-kv, In current Stackoverflow_Survey_Analysis.ipynb file. There is error in the get_group function I've also fixed this issue in PR. 
Screenshot 2024-05-14 211545

Please check it.

**Comment by Maryam-Sikander** [comment]
> `Stackoverflow_Survey_Analysis.ipynb`
Project Admin! Please check it now
If there's any issue please assist me in how I can send PR.

**Comment by Maryam-Sikander** [comment]
Hi @sanjay-kv, please let me know the issues with my PR so that I can fix them. I've added Catboost Regressor to the models and also fixed other issues in the notebook.

**Review by sanjay-kv — APPROVED** [review]
Good to go

**Comment by sanjay-kv** [comment]
@Maryam-Sikander can you work on this conflict issues

**Pull request closed without merging**
