### PR TITLE
Open Source Analysis #315

### PR DESCRIPTION
**Pull request by ChethanaPotukanam**
performed opensource_analysis on survey_results_sample_2018.csv.

### CODE REVIEW

**Comment by ChethanaPotukanam** [comment]
@sanjay-kv I completed the issue assigned to me.Please review the PR.Let me know if there are any mistakes.I will rectify them.

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
This doesnt make sense to me, we are building a single streamlit app to enhance the existing thing. 
Adding multiple individual ipynb is not what we looking for. 

+ don't see any respective issue you created for this.

**Comment by ChethanaPotukanam** [comment]
@sanjay-kv I would like to add an app.py file to the Streamlit folder. This file will incorporate the analysis performed in the Jupyter notebook into the Streamlit app, making all functionalities and visualizations accessible through the app interface. Is this acceptable?

**Comment by ChethanaPotukanam** [comment]
This PR address the issue #315

**Review by sanjay-kv — APPROVED** [review]
you need to create a folder and add into it.

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
