### PR TITLE
Added Other visualization

### PR DESCRIPTION
**Pull request by Pranali3103**
Added new visualization of Gender vs Location from where they do jobs .

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
I dont see the code changes while reviewing,

**Review by Pranali3103 — COMMENTED** [review]
I  added the new visualization for Gender vs Location from where they do work

**Comment by Pranali3103** [comment]
I have done changes in data -> images-> added one new visualization

**Comment by Satyam0775** [comment]
I would like to work on this issue. Please assign this task to me

**Comment by Pranali3103** [comment]
@sanjay-kv I added the Gender based Analysis of year 2022 , cleaned the data , filled the null values and replace some values which were in less amounts yet to be considered m, kindly review it

**Comment by Pranali3103** [comment]
Also if convenient please merge my pull request

**Comment by okaditya84** [comment]
@sanjay-kv Shall we merge this ?

**Comment by sanjay-kv** [comment]
No changes requested upon review. Once she make changes we will

**Comment by sanjay-kv** [comment]
Can we have 1:1 call sometime? @okaditya84 i hope u the assigned mentor for this repo right

**Comment by okaditya84** [comment]
> Can we have 1:1 call sometime? @okaditya84 i hope u the assigned mentor for this repo right

Yes kindly coordinate on discord. 
okaditya84

**Comment by Satyam0775** [comment]
"C:\Users\satya\git\Stackoverflow-Analysis\.ipynb_checkpoints\Stackoverflow_Survey_Analysis-checkpoint.ipynb"

**Comment by ChinmayNakwa** [comment]
I would like to work on this issue. Please assign this task to me under gssoc

**Pull request closed without merging**
