### PR TITLE
Make Issue template more visually appealing. #51

### PR DESCRIPTION
**Pull request by TonyStark-47**
Made this issue template looks great and added issue forms to the respective issues to make it easier for the contributor to raise it.

This issue has been raised here: #51 

I have made changes in these three files inside the Issue Templates:
- [Update and rename bug_report.md to bug_report.yml](https://github.com/Recode-Hive/Stackoverflow-Analysis/commit/ee806505dde6dd2d57dad3c40fd7a249d4df8e74)

- [Update and rename feature_request.md to feature_request.yml](https://github.com/Recode-Hive/Stackoverflow-Analysis/commit/e87c19c17b3be57036bc647bb5d9a75032865843)

- [Create documentation_update.yml](https://github.com/Recode-Hive/Stackoverflow-Analysis/commit/c418248efb7e8981f3eb2ae9e7aa65f5ee83add2)

### CODE REVIEW

**Comment by sanjay-kv** [comment]
Hi I liked your work, but as per the opensource practice its first come first serve basis assign of issue. There is already one person assigned to this issue. Is that person make the issue stale then I will consider this. 

Kindly do not put effort until you get issue assigned.

**Comment by TonyStark-47** [comment]
Okay.

**Comment by R1ya4git** [comment]
I would like to work on this please assign me this issue

**Comment by okaditya84** [comment]
> I would like to work on this please assign me this issue

This issue was already assigned.

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
Thanks @TonyStark-47 for being patient. Will make sure to PR asap going forward. i have upgraded level to 2

**Pull request merged**
