### PR TITLE
Fixing Issue #107 Learn.md File Index Not Linked

### PR DESCRIPTION
**Pull request by sanskritilabroo**
Linked all the table of contents properly to their respective sections in the learn.md file.
image

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
approved

**Comment by sanskritilabroo** [comment]
@sanjay-kv Sir, as this was a GSSOC level 1 issue, requesting if it possible to add the level 1 tag because this is not reflecting in my score on the leaderboard.

**Comment by sanjay-kv** [comment]
It was a link issue thats why not giving levels.

**Comment by sanjay-kv** [comment]
image
its there on leaderboard

**Pull request merged**
