### PR TITLE
Added analysis _2021

### PR DESCRIPTION
**Pull request by bhartijoshi04**

### CODE REVIEW

**Comment by bhartijoshi04** [comment]
Sir, you can add the level and gssoc.
I've added the file to the backlog folder.

**Comment by sanjay-kv** [comment]
Thanks for your patience and ready to work on the change requests I made, 

As a token of appreciation I merged without review, you will soon get a new badge on your profile from github for the same.

**Comment by bhartijoshi04** [comment]
> Thanks for your patience and ready to work on the change requests I made,
> 
> As a token of appreciation I merged without review, you will soon get a new badge on your profile from github for the same.

I appreciate it, sir, Thank you for guiding me.

**Comment by bhartijoshi04** [comment]
Sir, you've added level 2 previously to the same PR #118. I've closed it due to conflicts.

**Comment by sanjay-kv** [comment]
corrected it

**Pull request merged**
