### PR TITLE
Job Satisfaction Analysis

### PR DESCRIPTION
**Pull request by ranamanish674zu**
Target Variable: JobSatisfaction or CareerSatisfaction.
Predictors: Variables like Employment, YearsCodingProf, FormalEducation, CompanySize, DevType, etc.
Objective: Predict levels of job satisfaction based on personal and professional attributes
Predicting job satisfaction enables organizations to enhance employee well-being, reduce turnover, improve performance, tailor recruitment strategies, and foster a positive workplace culture.
here are some screenshot from the ipynb file->
image
image
image
@sanjay-kv complete issue #293 please review

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
this is not the right approach, you should be adding like enhancement to existing ipynb file. or web app.

**Comment by ranamanish674zu** [comment]
> this is not the right approach, you should be adding like enhancement to existing ipynb file. or web app.

okay sir

**Comment by ranamanish674zu** [comment]
@sanjay-kv  i have added a web app with streamlit on pkl model ....could you please review

**Comment by ranamanish674zu** [comment]
image

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
image
image


you are creating folder structure similar to documentation repos like machine learning repo. this is a deployment issue so here we should work on the enhancement of the existing project.

**Comment by ranamanish674zu** [comment]
> image image
> 
> you are creating folder structure similar to documentation repos like machine learning repo. this is a deployment issue so here we should work on the enhancement of the existing project.

@sanjay-kv do you mean i have to edit the folders which are stored in backlog folder according to my changes ?is it right sir ??

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
